[package]
name = "big_space"
version = "0.1.3"
edition = "2021"
description = "A floating origin plugin for bevy"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.10", default_features = false }
bevy_polyline = { version = "0.6", optional = true }

[dev-dependencies]
bevy = { version = "0.10", default_features = false, features = [
    "bevy_text",
    "bevy_ui",
    "bevy_render",
    "bevy_winit",
    "x11",
] }
bevy_framepace = "0.12"

[features]
default = ["debug"]
debug = ["bevy_polyline"]
