[package]
name = "big_space"
version = "0.1.0"
edition = "2021"
description = "A floating origin plugin for bevy"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.9", default_features = false }
bevy_rapier3d = { version = "0.19", optional = true }
bevy_polyline = "0.4"

[dev-dependencies]
bevy = { version = "0.9", default_features = false, features = [
    "bevy_render",
    "bevy_winit",
    "x11",
] }


[features]
rapier = ["bevy_rapier3d"]
