[package]
name = "big_space"
version = "0.7.0"
edition = "2021"
description = "A floating origin plugin for bevy"
license = "MIT OR Apache-2.0"
keywords = ["bevy", "floating-origin", "large-scale", "space"]
repository = "https://github.com/aevyrie/big_space"
documentation = "https://docs.rs/crate/big_space/latest"

[features]
default = []
debug = ["bevy_gizmos", "bevy_color"]
camera = ["bevy_render", "bevy_time", "bevy_input"]

[dependencies]
tracing = "0.1" # Less deps than pulling in bevy_log
bevy_app = { version = "0.14.0", default-features = false }
bevy_ecs = { version = "0.14.0", default-features = false }
bevy_hierarchy = { version = "0.14.0", default-features = false }
bevy_math = { version = "0.14.0", default-features = false }
bevy_reflect = { version = "0.14.0", default-features = false }
bevy_transform = { version = "0.14.0", default-features = false, features = [
    "bevy-support",
] }
bevy_utils = { version = "0.14.0", default-features = false }
# Optional
bevy_color = { version = "0.14.0", default-features = false, optional = true }
bevy_gizmos = { version = "0.14.0", default-features = false, optional = true }
bevy_render = { version = "0.14.0", default-features = false, optional = true }
bevy_input = { version = "0.14.0", default-features = false, optional = true }
bevy_time = { version = "0.14.0", default-features = false, optional = true }

[dev-dependencies]
big_space = { path = "", features = ["debug", "camera"] }
bevy = { version = "0.14.0", default-features = false, features = [
    "bevy_scene",
    "bevy_gltf",
    "bevy_winit",
    "default_font",
    "bevy_ui",
    "bevy_pbr",
    "bevy_gizmos",
    "x11",
    "tonemapping_luts",
    "multi_threaded",
] }
noise = "0.9"
turborand = "0.10"
criterion = "0.5"

[[bench]]
name = "benchmarks"
harness = false


[[example]]
name = "demo"
path = "examples/demo.rs"
doc-scrape-examples = true

[[example]]
name = "debug"
path = "examples/debug.rs"
doc-scrape-examples = true

[[example]]
name = "error"
path = "examples/error.rs"
doc-scrape-examples = true

[[example]]
name = "error_child"
path = "examples/error_child.rs"
doc-scrape-examples = true

[[example]]
name = "planets"
path = "examples/planets.rs"
doc-scrape-examples = true

[[example]]
name = "split_screen"
path = "examples/split_screen.rs"
doc-scrape-examples = true
