[package]
name = "big_space"
version = "0.3.0"
edition = "2021"
description = "A floating origin plugin for bevy"
license = "MIT OR Apache-2.0"
keywords = ["bevy", "floating-origin", "large-scale", "space"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.11", default_features = false }

[dev-dependencies]
bevy = "0.11"
bevy_framepace = "0.13"

[features]
default = ["debug"]
debug = ["bevy/bevy_gizmos"]
