on: 
  pull_request:
  push:
    branches:
      - main

name: CI

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable

      - name: Update Packages
        run: sudo apt-get update -yq
        
      - name: Install dependencies
        run: sudo apt-get install -yq --no-install-recommends libudev-dev libasound2-dev libxcb-composite0-dev
          
      - name: Cache Dependencies
        uses: Swatinem/rust-cache@ce325b60658c1b38465c06cc965b79baf32c1e72
      
      - name: Format
        run: cargo fmt --all -- --check
      
      - name: Check
        run: cargo check --all-targets
      
      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings
      
      - name: Test
        run: cargo test --all-targets
